# Site settings
title: Fortnum & Mason
client:
  name: Fortnum & Mason
  link: https://www.fortnumandmason.com/
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Enter below to be in with a chance of winning a night’s stay at The Athenaeum in London, an enviable five-star hotel set to indulge your fancies in one of the most exclusive areas of the city. Complement your opulent retreat with an extravagant Jamboree Hamper from Fortnum & Mason, packed with decadent delights for a truly luxurious getaway.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/fortnum-and-mason" # the subpath of your site, e.g. /blog/
img:     "/fortnum-and-mason/_assets/img"
css:     "/fortnum-and-mason/_assets/css"
js:      "/fortnum-and-mason/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed